name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # The branch you want to trigger the workflow on

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yourdockerhubusername/inventory-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: SSH to Local Server and Pull Latest Image
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LOCAL_SERVER_HOST }}
          username: ${{ secrets.LOCAL_SERVER_USERNAME }}
          key: ${{ secrets.LOCAL_SERVER_SSH_KEY }}
          script: |
            docker pull yourdockerhubusername/inventory-api:latest
            docker stop inventory-api || true
            docker rm inventory-api || true
            docker run -d --name inventory-api -p 8090:8080 yourdockerhubusername/inventory-api:latest
